
#GET STARTED DOCUMENTATION https://realpython.com/api-integration-in-python/

"""
    Function
    Then API Keys
    
    https://www.alphavantage.co/query?function=TIME_SERIES_INTRADAY&symbol=MSFT&interval=5min&apikey=demo
    
"""    
   
#FINANCE   
    #https://www.datadriveninvestor.com/2019/02/25/6-alternatives-to-the-yahoo-finance-api/
        #Google is gone
        #yahoo as well
    #Alternative https://www.datadriveninvestor.com/2019/02/25/6-alternatives-to-the-yahoo-finance-api/
        #https://www.alphavantage.co/
        #https://www.alphavantage.co/documentation/
